#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python /app/manage.py collectstatic --noinput
{% if cookiecutter.use_whitenoise == 'y' and cookiecutter.use_compressor == 'y' %}
compress_enabled() {
python << END
import sys

from environ import Env

env = Env(COMPRESS_ENABLED=(bool, True))
print('[BALLA] Compress enabled = %s' % env('COMPRESS_ENABLED'))
if env('COMPRESS_ENABLED'):
    sys.exit(0)
else:
    sys.exit(1)

END
}

if compress_enabled;
then
  echo "[BALLA] Running python /app/manage.py compress"
  # NOTE this command will fail if django-compressor is disabled
  python /app/manage.py compress
  echo "[BALLA] Done with compress"
else
  echo "[BALLA] No compress ran as detected as disabled"
fi
{%- endif %}
/usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:5000 --chdir=/app
